PKG_NAME="mihowrt"
PKG_VERSION="0.5"
PKG_CONFIG="mihowrt"
PKG_TMP_DIR="/tmp/mihowrt"
PKG_STATE_DIR="/var/run/mihowrt"
PKG_PERSIST_DIR="/etc/mihowrt"

CLASH_DIR="/opt/clash"
CLASH_BIN="$CLASH_DIR/bin/clash"
CLASH_CONFIG="$CLASH_DIR/config.yaml"
LIST_DIR="$CLASH_DIR/lst"
DST_LIST_FILE="$LIST_DIR/always_proxy_dst.txt"
SRC_LIST_FILE="$LIST_DIR/always_proxy_src.txt"
DIRECT_DST_LIST_FILE="$LIST_DIR/direct_dst.txt"
RULESET_TMPFS="/tmp/clash/ruleset"
RULESET_LINK="$CLASH_DIR/ruleset"
PROXY_PROVIDERS_TMPFS="/tmp/clash/proxy_providers"
PROXY_PROVIDERS_LINK="$CLASH_DIR/proxy_providers"
CACHE_DB_TMPFS="/tmp/clash/cache.db"
CACHE_DB_LINK="$CLASH_DIR/cache.db"

DNS_BACKUP_FILE="$PKG_PERSIST_DIR/dns.backup"
DNS_RUNTIME_BACKUP_FILE="$PKG_STATE_DIR/dns.backup"
DNS_AUTO_RESOLVFILE="/tmp/resolv.conf.d/resolv.conf.auto"
SERVICE_PID_FILE="$PKG_STATE_DIR/mihomo.pid"
ROUTE_STATE_FILE="$PKG_STATE_DIR/route.state"

NFT_TABLE_NAME="mihowrt"
NFT_LEGACY_TABLE_NAMES="mihomo_podkop"
NFT_PROXY_DST_SET="proxy_dst"
NFT_PROXY_SRC_SET="proxy_src"
NFT_DIRECT_DST_SET="direct_dst"
NFT_LOCALV4_SET="localv4"
NFT_IFACE_SET="source_ifaces"
NFT_CHAIN_DNS_HIJACK="dns_hijack"
NFT_CHAIN_PREROUTING="mangle_prerouting"
NFT_CHAIN_PREROUTING_POLICY="prerouting_policy"
NFT_CHAIN_OUTPUT="mangle_output"
NFT_CHAIN_PROXY="proxy_redirect"
NFT_INTERCEPT_MARK="0x00001000"

ROUTE_TABLE_ID_AUTO_MIN="200"
ROUTE_TABLE_ID_AUTO_MAX="252"
ROUTE_RULE_PRIORITY_AUTO_MIN="10000"
ROUTE_RULE_PRIORITY_AUTO_MAX="10999"
