#!/usr/bin/env bash

set -euo pipefail

source "$(dirname "$0")/testlib.sh"

tmpdir="$(make_temp_dir)"
trap 'rm -rf "$tmpdir"' EXIT

tmpbin="$tmpdir/bin"
mkdir -p "$tmpbin"

cat >"$tmpbin/logger" <<'EOF'
#!/usr/bin/env bash
exit 0
EOF

chmod +x "$tmpbin/logger"
export PATH="$tmpbin:$PATH"
export CLASH_CONFIG="$tmpdir/config.yaml"

source "$ROOT_DIR/rootfs/usr/lib/mihowrt/helpers.sh"

assert_eq "5353" "$(port_from_addr '127.0.0.1:5353')" "port_from_addr parses IPv4 host:port"
assert_eq "7874" "$(port_from_addr '[::]:7874')" "port_from_addr parses bracketed IPv6 host:port"
assert_false "port_from_addr should reject plain IPv6 address" port_from_addr "2001:db8::1"
assert_eq "127.0.0.1#7874" "$(normalize_dns_server_target '0.0.0.0#7874')" "normalize_dns_server_target rewrites wildcard IPv4"
assert_eq "127.0.0.1#7874" "$(normalize_dns_server_target '[::]#7874')" "normalize_dns_server_target rewrites wildcard IPv6"
assert_eq "127.0.0.1#7874" "$(normalize_dns_server_target_from_addr '0.0.0.0:7874')" "normalize_dns_server_target_from_addr rewrites wildcard IPv4"
assert_eq "192.168.70.1#7874" "$(normalize_dns_server_target_from_addr '192.168.70.1:7874')" "normalize_dns_server_target_from_addr preserves bound IPv4 host"
assert_eq "value" "$(yaml_cleanup_scalar '  value   # comment')" "yaml_cleanup_scalar trims inline comment"
assert_eq "quoted value" "$(yaml_cleanup_scalar '"quoted value"')" "yaml_cleanup_scalar strips double quotes"
assert_eq "single quoted" "$(yaml_cleanup_scalar "'single quoted'")" "yaml_cleanup_scalar strips single quotes"

patch_candidate="$tmpdir/marker-config.yaml"
cat >"$patch_candidate" <<'EOF'
%YAML 1.2
---
tproxy-port: 7894
routing-mark: 2

dns:
  listen: 0.0.0.0:7874
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.0/15
EOF

yaml_prepend_autogenerated_scalars "$patch_candidate" "mihomo.sock" "192.168.1.1:9090" "abcdef0123456789"
assert_eq "%YAML 1.2" "$(sed -n '1p' "$patch_candidate")" "yaml_prepend_autogenerated_scalars should preserve YAML directive"
assert_eq "---" "$(sed -n '2p' "$patch_candidate")" "yaml_prepend_autogenerated_scalars should keep document marker before generated scalars"
assert_eq "# MihoWRT autogenerated API defaults" "$(sed -n '3p' "$patch_candidate")" "yaml_prepend_autogenerated_scalars should insert defaults after YAML header"
CLASH_CONFIG="$patch_candidate"
patched_json="$(read_config_json)"
assert_eq "mihomo.sock" "$(printf '%s\n' "$patched_json" | jq -r '.external_controller_unix')" "patched YAML should expose autogenerated Unix controller"
assert_eq "192.168.1.1:9090" "$(printf '%s\n' "$patched_json" | jq -r '.external_controller')" "patched YAML should expose autogenerated IP controller"
assert_eq "abcdef0123456789" "$(printf '%s\n' "$patched_json" | jq -r '.secret')" "patched YAML should expose autogenerated secret"
assert_eq "0" "$(printf '%s\n' "$patched_json" | jq -r '.errors | length')" "patched YAML with document marker should stay parseable"
CLASH_CONFIG="$tmpdir/config.yaml"

cat >"$CLASH_CONFIG" <<'EOF'
mode: rule
port: 7890
socks-port: 7891
mixed-port: 7892
redir-port: 7893
allow-lan: true
bind-address: 127.0.0.1
tproxy-port: 7894
routing-mark: 2
external-controller: 0.0.0.0:9090
external-controller-tls: :9443
external-controller-unix: mihomo.sock
external-controller-pipe: mihomo.pipe
external-controller-cors:
  allow-origins:
    - '*'
  allow-private-network: true
external-doh-server: /dns-query
secret: "abc123"
external-ui: ./ui
external-ui-name: zashboard
tls:
  certificate: ./server.crt
  private-key: ./server.key
  client-auth-type: require-and-verify
  client-auth-cert: ./client-ca.crt
  ech-key: |
    -----BEGIN ECH KEYS-----
    abc
    -----END ECH KEYS-----

dns:
  listen: 0.0.0.0:7874
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.0/15
EOF

config_json="$(read_config_json)"

assert_eq "7874" "$(printf '%s\n' "$config_json" | jq -r '.dns_port')" "read_config_json extracts dns port"
assert_eq "127.0.0.1#7874" "$(printf '%s\n' "$config_json" | jq -r '.mihomo_dns_listen')" "read_config_json normalizes dns listen target"
assert_eq "7890" "$(printf '%s\n' "$config_json" | jq -r '.port')" "read_config_json extracts HTTP port"
assert_eq "7891" "$(printf '%s\n' "$config_json" | jq -r '.socks_port')" "read_config_json extracts SOCKS port"
assert_eq "7892" "$(printf '%s\n' "$config_json" | jq -r '.mixed_port')" "read_config_json extracts mixed port"
assert_eq "7893" "$(printf '%s\n' "$config_json" | jq -r '.redir_port')" "read_config_json extracts redirect port"
assert_eq "true" "$(printf '%s\n' "$config_json" | jq -r '.allow_lan')" "read_config_json extracts allow-lan"
assert_eq "127.0.0.1" "$(printf '%s\n' "$config_json" | jq -r '.bind_address')" "read_config_json extracts bind-address"
assert_eq "7894" "$(printf '%s\n' "$config_json" | jq -r '.tproxy_port')" "read_config_json extracts tproxy port"
assert_eq "2" "$(printf '%s\n' "$config_json" | jq -r '.routing_mark')" "read_config_json extracts routing mark"
assert_eq "true" "$(printf '%s\n' "$config_json" | jq -r '.catch_fakeip')" "read_config_json enables fake-ip catch"
assert_eq "198.18.0.0/15" "$(printf '%s\n' "$config_json" | jq -r '.fake_ip_range')" "read_config_json extracts fake-ip range"
assert_eq "mihomo.sock" "$(printf '%s\n' "$config_json" | jq -r '.external_controller_unix')" "read_config_json extracts Unix controller socket"
assert_eq "mihomo.pipe" "$(printf '%s\n' "$config_json" | jq -r '.external_controller_pipe')" "read_config_json extracts named pipe controller"
assert_eq "/dns-query" "$(printf '%s\n' "$config_json" | jq -r '.external_doh_server')" "read_config_json extracts external DoH server path"
assert_eq "true" "$(printf '%s\n' "$config_json" | jq -r '.external_controller_cors | contains("allow-private-network: true")')" "read_config_json extracts controller CORS block"
assert_eq "true" "$(printf '%s\n' "$config_json" | jq -r '.api_tls | contains("client-auth-type: require-and-verify")')" "read_config_json extracts API TLS block"
assert_eq "true" "$(printf '%s\n' "$config_json" | jq -r '.api_tls | contains("ech-key: |")')" "read_config_json extracts API TLS ECH key"
assert_eq "zashboard" "$(printf '%s\n' "$config_json" | jq -r '.external_ui_name')" "read_config_json extracts external UI name"
assert_eq "0" "$(printf '%s\n' "$config_json" | jq -r '.errors | length')" "read_config_json should not emit errors for valid config"

cat >"$CLASH_CONFIG" <<'EOF'
tproxy-port: 7894
routing-mark: 2

dns:
  listen: 192.168.70.1:7874
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.0/15
EOF

bound_json="$(read_config_json)"

assert_eq "7874" "$(printf '%s\n' "$bound_json" | jq -r '.dns_port')" "read_config_json should keep dns port for bound host"
assert_eq "192.168.70.1#7874" "$(printf '%s\n' "$bound_json" | jq -r '.mihomo_dns_listen')" "read_config_json should preserve non-loopback dns.listen host"
assert_eq "0" "$(printf '%s\n' "$bound_json" | jq -r '.errors | length')" "read_config_json should accept valid bound host"

cat >"$CLASH_CONFIG" <<'EOF'
tproxy-port: 7894
routing-mark: 2

dns:
  listen: 0.0.0.0:7874
EOF

missing_mode_json="$(read_config_json)"

assert_eq "true" "$(printf '%s\n' "$missing_mode_json" | jq -r 'any(.errors[]; contains("Missing dns.enhanced-mode"))')" "read_config_json should require dns.enhanced-mode"

cat >"$CLASH_CONFIG" <<'EOF'
tproxy-port: 7894
routing-mark: 2

dns:
  listen: 0.0.0.0:7874
  enhanced-mode: redir-host
  fake-ip-range: 198.18.0.0/15
EOF

redir_host_json="$(read_config_json)"

assert_eq "true" "$(printf '%s\n' "$redir_host_json" | jq -r 'any(.errors[]; contains("fake-ip is required"))')" "read_config_json should reject non fake-ip enhanced modes"

cat >"$CLASH_CONFIG" <<'EOF'
# parser should keep quoted scalars intact and ignore unrelated nested dns keys
external-ui-name: "meta cube"
external-controller: "127.0.0.1:9090#frag"
external-controller-unix: "mihomo custom.sock"
external-ui: "./ui bundle"
secret: "abc#123"
routing-mark: 100
tproxy-port: "7894"

dns:
  fake-ip-filter:
    - "+.lan"
  listen: "0.0.0.0:5353"
  enhanced-mode: fake-ip # inline comment
  fake-ip-range: "198.18.0.0/15"
EOF

quoted_json="$(read_config_json)"

assert_eq "5353" "$(printf '%s\n' "$quoted_json" | jq -r '.dns_port')" "read_config_json should parse quoted dns.listen"
assert_eq "127.0.0.1#5353" "$(printf '%s\n' "$quoted_json" | jq -r '.mihomo_dns_listen')" "read_config_json should normalize quoted dns.listen"
assert_eq "127.0.0.1:9090#frag" "$(printf '%s\n' "$quoted_json" | jq -r '.external_controller')" "read_config_json should preserve quoted controller with hash"
assert_eq "mihomo custom.sock" "$(printf '%s\n' "$quoted_json" | jq -r '.external_controller_unix')" "read_config_json should preserve quoted Unix controller socket"
assert_eq "abc#123" "$(printf '%s\n' "$quoted_json" | jq -r '.secret')" "read_config_json should preserve quoted secret with hash"
assert_eq "meta cube" "$(printf '%s\n' "$quoted_json" | jq -r '.external_ui_name')" "read_config_json should preserve spaced external UI name"
assert_eq "0" "$(printf '%s\n' "$quoted_json" | jq -r '.errors | length')" "read_config_json should ignore unrelated nested dns keys"

cat >"$CLASH_CONFIG" <<'EOF'
external-controller: "127.0.0.1:9090" # inline comment
secret: "abc#123" # inline comment
tproxy-port: "7894" # inline comment
routing-mark: "100" # inline comment

dns:
  listen: "0.0.0.0:5353" # inline comment
  enhanced-mode: fake-ip # inline comment
  fake-ip-range: "198.18.0.0/15" # inline comment
EOF

quoted_comment_json="$(read_config_json)"

assert_eq "5353" "$(printf '%s\n' "$quoted_comment_json" | jq -r '.dns_port')" "read_config_json should parse quoted dns.listen with trailing comment"
assert_eq "7894" "$(printf '%s\n' "$quoted_comment_json" | jq -r '.tproxy_port')" "read_config_json should parse quoted tproxy-port with trailing comment"
assert_eq "100" "$(printf '%s\n' "$quoted_comment_json" | jq -r '.routing_mark')" "read_config_json should parse quoted routing-mark with trailing comment"
assert_eq "abc#123" "$(printf '%s\n' "$quoted_comment_json" | jq -r '.secret')" "read_config_json should preserve hash inside quoted secret before trailing comment"
assert_eq "198.18.0.0/15" "$(printf '%s\n' "$quoted_comment_json" | jq -r '.fake_ip_range')" "read_config_json should parse quoted fake-ip-range with trailing comment"
assert_eq "0" "$(printf '%s\n' "$quoted_comment_json" | jq -r '.errors | length')" "read_config_json should accept valid quoted scalars with trailing comments"

cat >"$CLASH_CONFIG" <<'EOF'
tproxy-port: bad
routing-mark: 4294967296

dns:
  listen: not-an-addr
  enhanced-mode: fake-ip
EOF

invalid_json="$(read_config_json)"

assert_eq "4" "$(printf '%s\n' "$invalid_json" | jq -r '.errors | length')" "read_config_json should emit expected error count"
assert_eq "true" "$(printf '%s\n' "$invalid_json" | jq -r 'any(.errors[]; contains("Invalid dns.listen"))')" "read_config_json should report invalid dns.listen"
assert_eq "true" "$(printf '%s\n' "$invalid_json" | jq -r 'any(.errors[]; contains("Invalid tproxy-port"))')" "read_config_json should report invalid tproxy-port"
assert_eq "true" "$(printf '%s\n' "$invalid_json" | jq -r 'any(.errors[]; contains("Invalid routing-mark"))')" "read_config_json should report invalid routing mark"
assert_eq "true" "$(printf '%s\n' "$invalid_json" | jq -r 'any(.errors[]; contains("Missing dns.fake-ip-range"))')" "read_config_json should report missing fake-ip range"

cat >"$CLASH_CONFIG" <<'EOF'
tproxy-port: 7894
routing-mark: 2
dns: *shared_dns
EOF

alias_json="$(read_config_json)"

assert_eq "true" "$(printf '%s\n' "$alias_json" | jq -r 'any(.errors[]; contains("Missing dns.listen"))')" "read_config_json should fail closed when dns block comes from alias"

pass "config parsing helpers"
