#!/usr/bin/env bash

set -euo pipefail

source "$(dirname "$0")/testlib.sh"

tmpdir="$(make_temp_dir)"
trap 'rm -rf "$tmpdir"' EXIT

tmpbin="$tmpdir/bin"
mkdir -p "$tmpbin"

cat >"$tmpbin/logger" <<'EOF'
#!/usr/bin/env bash
exit 0
EOF

cat >"$tmpbin/clash" <<'EOF'
#!/usr/bin/env bash
config=""

while [ "$#" -gt 0 ]; do
	case "$1" in
		-f)
			config="$2"
			shift 2
			;;
		*)
			shift
			;;
	esac
done

if grep -q 'bad-syntax: yes' "$config"; then
	printf '%s\n' 'syntax bad' >&2
	exit 1
fi

exit 0
EOF

cat >"$tmpbin/uci" <<'EOF'
#!/usr/bin/env bash
if [[ "${1:-}" == "-q" ]]; then
	shift
fi

case "${1:-}:${2:-}" in
	get:network.lan.ipaddr)
		printf '%s\n' "${TEST_ROUTER_IP:-192.168.7.1}"
		;;
	get:network.lan.device)
		printf '%s\n' "br-lan"
		;;
	*)
		exit 1
		;;
esac
EOF

cat >"$tmpbin/hexdump" <<'EOF'
#!/usr/bin/env bash
cat >/dev/null
printf '%s' '0123456789abcdef0123456789abcdef0123456789abcdef'
EOF

chmod +x "$tmpbin/logger" "$tmpbin/clash" "$tmpbin/uci" "$tmpbin/hexdump"
export PATH="$tmpbin:$PATH"
export CLASH_DIR="$tmpdir/opt/clash"
export CLASH_BIN="$tmpbin/clash"
export CLASH_CONFIG="$tmpdir/opt/clash/config.yaml"
export PKG_TMP_DIR="$tmpdir/run"

mkdir -p "$CLASH_DIR"
cat >"$CLASH_CONFIG" <<'EOF'
mode: rule
tproxy-port: 7894
routing-mark: 1

dns:
  listen: 0.0.0.0:7874
EOF

source "$ROOT_DIR/rootfs/usr/lib/mihowrt/helpers.sh"

cat >"$tmpdir/expected.yaml" <<'EOF'
mode: rule
tproxy-port: 7894
routing-mark: 2

dns:
  listen: 0.0.0.0:7874
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.0/15
EOF

cat >"$tmpdir/expected-patched.yaml" <<'EOF'
# MihoWRT autogenerated API defaults
external-controller-unix: mihomo.sock
external-controller: 192.168.7.1:9090
secret: 0123456789abcdef0123456789abcdef0123456789abcdef

mode: rule
tproxy-port: 7894
routing-mark: 2

dns:
  listen: 0.0.0.0:7874
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.0/15
EOF

candidate_valid="$tmpdir/candidate-valid.yaml"
cp "$tmpdir/expected.yaml" "$candidate_valid"
apply_config_file "$candidate_valid"
cmp -s "$CLASH_CONFIG" "$tmpdir/expected-patched.yaml" || fail "apply_config_file should patch and install validated config"
cmp -s "$CLASH_CONFIG" "$(validated_config_stamp_file)" || fail "apply_config_file should record active config as validated after install"
[[ ! -e "$candidate_valid" ]] || fail "apply_config_file should remove temp candidate after success"
compgen -G "$CLASH_CONFIG.tmp.*" >/dev/null && fail "apply_config_file should not leave flash-side temp config after success"

tmp_candidates_before="$(find /tmp -maxdepth 1 -name 'mihowrt-config.*' -print | sort)"
expected_contents="$(
	cat "$tmpdir/expected.yaml"
	printf '\001'
)"
expected_contents="${expected_contents%$'\001'}"
apply_config_contents "$expected_contents"
tmp_candidates_after="$(find /tmp -maxdepth 1 -name 'mihowrt-config.*' -print | sort)"
cmp -s "$CLASH_CONFIG" "$tmpdir/expected-patched.yaml" || fail "apply_config_contents should patch and install validated config"
cmp -s "$CLASH_CONFIG" "$(validated_config_stamp_file)" || fail "apply_config_contents should refresh validated config marker"
assert_eq "$tmp_candidates_before" "$tmp_candidates_after" "apply_config_contents should clean up staged /tmp config file"
compgen -G "$CLASH_CONFIG.tmp.*" >/dev/null && fail "apply_config_contents should not leave flash-side temp config after success"

candidate_same="$tmpdir/candidate-same.yaml"
cp "$CLASH_CONFIG" "$candidate_same"
before_mtime="$(stat -c %Y "$CLASH_CONFIG")"
sleep 1
apply_config_file "$candidate_same"
after_mtime="$(stat -c %Y "$CLASH_CONFIG")"
assert_eq "$before_mtime" "$after_mtime" "apply_config_file should skip replacing identical config to avoid extra flash writes"
cmp -s "$CLASH_CONFIG" "$(validated_config_stamp_file)" || fail "apply_config_file should keep validated config marker after identical-config no-op"
[[ ! -e "$candidate_same" ]] || fail "apply_config_file should remove temp candidate after identical-config no-op"

candidate_custom_api="$tmpdir/candidate-custom-api.yaml"
cat >"$candidate_custom_api" <<'EOF'
mode: rule
tproxy-port: 7894
routing-mark: 3
external-controller: 127.0.0.1:19090
external-controller-unix: custom.sock
secret: user-secret

dns:
  listen: 0.0.0.0:7874
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.0/15
EOF

apply_config_file "$candidate_custom_api"
assert_file_contains "$CLASH_CONFIG" "external-controller-unix: custom.sock" "apply_config_file should preserve custom Unix controller socket"
assert_file_contains "$CLASH_CONFIG" "external-controller: 127.0.0.1:19090" "apply_config_file should preserve custom external-controller"
assert_file_contains "$CLASH_CONFIG" "secret: user-secret" "apply_config_file should preserve custom API secret"
assert_file_not_contains "$CLASH_CONFIG" "external-controller-unix: mihomo.sock" "apply_config_file should not force default socket over an existing socket"
assert_file_not_contains "$CLASH_CONFIG" "0123456789abcdef0123456789abcdef0123456789abcdef" "apply_config_file should not overwrite existing secret"

candidate_missing_secret="$tmpdir/candidate-missing-secret.yaml"
cat >"$candidate_missing_secret" <<'EOF'
mode: rule
tproxy-port: 7894
routing-mark: 4
external-controller: 127.0.0.1:19090
external-controller-unix: custom.sock

dns:
  listen: 0.0.0.0:7874
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.0/15
EOF

apply_config_file "$candidate_missing_secret"
assert_file_contains "$CLASH_CONFIG" "external-controller-unix: custom.sock" "apply_config_file should preserve custom socket while generating missing secret"
assert_file_contains "$CLASH_CONFIG" "external-controller: 127.0.0.1:19090" "apply_config_file should preserve custom controller while generating missing secret"
assert_file_contains "$CLASH_CONFIG" "secret: user-secret" "apply_config_file should reuse active secret when candidate secret is missing"
assert_file_not_contains "$CLASH_CONFIG" "0123456789abcdef0123456789abcdef0123456789abcdef" "apply_config_file should not regenerate secret while active secret exists"

cp "$CLASH_CONFIG" "$tmpdir/live-before-invalid.yaml"
candidate_parse="$tmpdir/candidate-parse.yaml"
cat >"$candidate_parse" <<'EOF'
mode: rule
tproxy-port: 7894

dns:
  listen: 0.0.0.0:7874
EOF

assert_false "apply_config_file should reject policy-invalid config" apply_config_file "$candidate_parse"
cmp -s "$CLASH_CONFIG" "$tmpdir/live-before-invalid.yaml" || fail "apply_config_file should keep old config on policy validation failure"
cmp -s "$CLASH_CONFIG" "$(validated_config_stamp_file)" || fail "apply_config_file should preserve previous validated marker after policy validation failure"
[[ ! -e "$candidate_parse" ]] || fail "apply_config_file should remove temp candidate after policy validation failure"
compgen -G "$CLASH_CONFIG.tmp.*" >/dev/null && fail "apply_config_file should not leave flash-side temp config after policy validation failure"

candidate_mark_conflict="$tmpdir/candidate-mark-conflict.yaml"
cat >"$candidate_mark_conflict" <<'EOF'
mode: rule
tproxy-port: 7894
routing-mark: 4096

dns:
  listen: 0.0.0.0:7874
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.0/15
EOF

assert_false "apply_config_file should reject routing mark conflicts" apply_config_file "$candidate_mark_conflict"
cmp -s "$CLASH_CONFIG" "$tmpdir/live-before-invalid.yaml" || fail "apply_config_file should keep old config on routing mark conflict"
cmp -s "$CLASH_CONFIG" "$(validated_config_stamp_file)" || fail "apply_config_file should preserve previous validated marker after routing mark conflict"
[[ ! -e "$candidate_mark_conflict" ]] || fail "apply_config_file should remove temp candidate after routing mark conflict"
compgen -G "$CLASH_CONFIG.tmp.*" >/dev/null && fail "apply_config_file should not leave flash-side temp config after routing mark conflict"

candidate_syntax="$tmpdir/candidate-syntax.yaml"
cat >"$candidate_syntax" <<'EOF'
mode: rule
bad-syntax: yes
tproxy-port: 7894
routing-mark: 9

dns:
  listen: 0.0.0.0:7874
EOF

assert_false "apply_config_file should reject Mihomo syntax-invalid config" apply_config_file "$candidate_syntax"
cmp -s "$CLASH_CONFIG" "$tmpdir/live-before-invalid.yaml" || fail "apply_config_file should keep old config on syntax validation failure"
cmp -s "$CLASH_CONFIG" "$(validated_config_stamp_file)" || fail "apply_config_file should preserve previous validated marker after syntax validation failure"
[[ ! -e "$candidate_syntax" ]] || fail "apply_config_file should remove temp candidate after syntax validation failure"
compgen -G "$CLASH_CONFIG.tmp.*" >/dev/null && fail "apply_config_file should not leave flash-side temp config after syntax validation failure"

assert_true "current_config_has_validated_stamp should accept unchanged validated config" current_config_has_validated_stamp
printf '%s\n' '# external edit' >>"$CLASH_CONFIG"
assert_false "current_config_has_validated_stamp should reject externally modified config" current_config_has_validated_stamp

pass "config apply helper"
